### ISSUE TITLE
Cannot initizalize ESP

### ISSUE THREAD

**Issue by SeaTechRC** [zauberzeug/field_friend#10]
Hello.

In order to initialize the ESP, the robot brain has to configure some of its GPIO pins. (rosys/hardware/robot_brain.py enable_esp)
Since the container runs rosys as user "zauberzeug", it does not have the permissions to write to /sys/class/gpio/export or /sys/class/gpio/unexport.
![image](https://github.com/zauberzeug/field_friend/assets/153106523/3f3e0c2f-bb42-4be3-9dde-f5ca128646c5)
![image](https://github.com/zauberzeug/field_friend/assets/153106523/2afcfe66-9814-42a4-bfa7-1157a6a36d64)

**Comment by angelom93** [comment]
Hello SeaTechRC,

Thank you for reporting this issue. After thorough investigation, we've determined that the bug you've encountered is rooted in how RoSys handles the enabling of the ESP module. Specifically, it involves the initialization process where the robot's brain needs to configure certain GPIO pins to activate the ESP (as found in `rosys/hardware/robot_brain.py` under the `enable_esp` function). The challenge arises because the container running RoSys operates under the user "zauberzeug", which lacks the necessary permissions to write to `/sys/class/gpio/export` or `/sys/class/gpio/unexport`.

The resolution will be included in the next release of both Lizard and RoSys. This update will address the permission issues, ensuring that the field_friend system can correctly initialize the ESP without encountering permission-related errors.

**Comment by angelom93** [comment]
The issue was solved with the RoSys release [v0.10.2](https://github.com/zauberzeug/rosys/releases/tag/v0.10.2) and the Lizard Release [lizard_v0.1.8](https://github.com/zauberzeug/lizard/releases/tag/v0.1.8).
