### ISSUE TITLE
Robot turns on spot

### ISSUE THREAD

**Issue by pascalzauberzeug** [zauberzeug/field_friend#119]
The robot still turns on spot without moving forwards when using the straight line navigation.
Tested with F13/RB36 on https://github.com/zauberzeug/field_friend/pull/96, but I don't think it is related to the changes done there.

![1000003070](https://github.com/user-attachments/assets/567b59be-585f-4d5d-9d67-103553354ace)

![Screenshot 2024-07-16 at 15-46-57 Field Friend](https://github.com/user-attachments/assets/900b846a-607b-4bbc-984e-3aad630b639f)

```
rosys_1       | 2024-07-16 15:39:37.586 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:37.690 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:37.791 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:37.891 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:37.992 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:38.092 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:38.196 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:39:38.296 [INFO] field_friend/hardware/tornado.py:242: Ref ground not triggered: Bottom ground reached
rosys_1       | 2024-07-16 15:39:38.297 [INFO] field_friend/hardware/tornado.py:251: finalizing moving z axis down
rosys_1       | 2024-07-16 15:39:46.723 [INFO] field_friend/hardware/tornado.py:207: moving z axis to 0
rosys_1       | 2024-07-16 15:39:49.051 [INFO] field_friend/hardware/tornado.py:212: z axis moved to 0
rosys_1       | 2024-07-16 15:39:52.971 [INFO] field_friend/automations/puncher.py:105: punched at -0.02 with depth 0.01, now back to rest position "reference"
rosys_1       | 2024-07-16 15:39:52.972 [INFO] field_friend/automations/implements/weeding_implement.py:91: workflow completed
rosys_1       | 2024-07-16 15:39:52.973 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.13, -0.03) to Point(0.13, -0.03) by 0.004740341087867542 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.13, 0.0)
rosys_1       | 2024-07-16 15:39:52.974 [INFO] field_friend/automations/implements/tornado.py:64: Skipping weed because it was already punched
rosys_1       | 2024-07-16 15:39:53.586 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.12, -0.03) to Point(0.12, -0.03) by 0.004740484667725961 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.11, 0.0)
rosys_1       | 2024-07-16 15:39:53.587 [INFO] field_friend/automations/implements/tornado.py:64: Skipping weed because it was already punched
rosys_1       | 2024-07-16 15:39:54.003 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.1, -0.02) to Point(0.1, -0.03) by 0.005229677636585651 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.09, 0.0)
rosys_1       | 2024-07-16 15:39:54.004 [INFO] field_friend/automations/implements/tornado.py:82: Targeting crop 9a78e552-4615-4daa-894c-3a818fbc6316 which is 0.08091422189536067 away at world: Point(-0.36, -2.78), local: Point(0.09, 0.0)
rosys_1       | 2024-07-16 15:39:54.511 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.08, -0.03) to Point(0.08, -0.03) by 0.005571287367279465 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.08, 0.0)
rosys_1       | 2024-07-16 15:39:54.512 [INFO] field_friend/automations/implements/tornado.py:82: Targeting crop 9a78e552-4615-4daa-894c-3a818fbc6316 which is 0.06432214687245745 away at world: Point(-0.36, -2.78), local: Point(0.08, 0.0)
rosys_1       | 2024-07-16 15:39:54.918 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.06, -0.03) to Point(0.06, -0.03) by 0.00563157202652103 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.06, 0.0)
rosys_1       | 2024-07-16 15:39:54.919 [INFO] field_friend/automations/implements/tornado.py:82: Targeting crop 9a78e552-4615-4daa-894c-3a818fbc6316 which is 0.04452849722041616 away at world: Point(-0.36, -2.79), local: Point(0.06, 0.0)
rosys_1       | 2024-07-16 15:39:57.442 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.01, -0.03) to Point(0.01, -0.03) by 0.004958876874267788 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.02, 0.0)
rosys_1       | 2024-07-16 15:39:57.443 [INFO] field_friend/automations/implements/tornado.py:26: Performing Tornado Workflow..
rosys_1       | 2024-07-16 15:39:57.443 [INFO] field_friend/automations/implements/tornado.py:32: Drilling crop at Point(-0.35, -2.78) with angle 30.0°
rosys_1       | 2024-07-16 15:39:57.444 [INFO] field_friend/automations/puncher.py:67: Punching at 0.0038732758021282994 with depth 0.01...
rosys_1       | 2024-07-16 15:39:57.444 [INFO] field_friend/hardware/y_axis.py:47: moving yaxis to 0.0038732758021282994 with speed 500
rosys_1       | 2024-07-16 15:39:57.444 [INFO] field_friend/hardware/y_axis_canopen_hardware.py:76: moving to steps: 105738
rosys_1       | 2024-07-16 15:39:59.352 [INFO] field_friend/hardware/y_axis_canopen_hardware.py:89: yaxis moved to 0.0038732758021282994
rosys_1       | 2024-07-16 15:39:59.353 [INFO] field_friend/automations/puncher.py:163: Drilling with tornado at 30.0°...
rosys_1       | 2024-07-16 15:39:59.353 [INFO] field_friend/hardware/tornado.py:220: moving z axis down
rosys_1       | 2024-07-16 15:40:00.356 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:00.458 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:00.559 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:00.660 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:00.763 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:00.864 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:00.977 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.078 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.178 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.280 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.380 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.481 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.581 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.683 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.784 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.885 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:01.985 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:02.085 [INFO] field_friend/hardware/tornado.py:237: moving z axis down
rosys_1       | 2024-07-16 15:40:02.185 [INFO] field_friend/hardware/tornado.py:242: Ref ground not triggered: Bottom ground reached
rosys_1       | 2024-07-16 15:40:02.185 [INFO] field_friend/hardware/tornado.py:251: finalizing moving z axis down
rosys_1       | 2024-07-16 15:40:10.556 [INFO] field_friend/hardware/tornado.py:207: moving z axis to 0
rosys_1       | 2024-07-16 15:40:12.862 [INFO] field_friend/hardware/tornado.py:212: z axis moved to 0
rosys_1       | 2024-07-16 15:40:13.872 [WARNING] rosys/rosys.py:232: less than 300 mb of memory remaining -> start garbage collection
rosys_1       | 2024-07-16 15:40:14.245 [INFO] field_friend/localization/gnss_hardware.py:102: Parse error: ('could not parse data', '$')
rosys_1       | 2024-07-16 15:40:14.246 [WARNING] field_friend/localization/gnss_hardware.py:109: No location in GNSS data -- maybe it was provided in GGA message?
rosys_1       | 2024-07-16 15:40:14.247 [WARNING] field_friend/localization/gnss.py:94: new GNSS record is None
rosys_1       | 2024-07-16 15:40:14.247 [INFO] field_friend/automations/automation_watcher.py:62: not pausing automation because GNSS connection lost but GNSS watch is not active
rosys_1       | 2024-07-16 15:40:15.233 [WARNING] rosys/rosys.py:235: finished garbage collection
rosys_1       | 2024-07-16 15:40:16.679 [INFO] field_friend/automations/puncher.py:105: punched at 0.00 with depth 0.01, now back to rest position "reference"
rosys_1       | 2024-07-16 15:40:16.680 [INFO] field_friend/automations/implements/weeding_implement.py:91: workflow completed
rosys_1       | 2024-07-16 15:40:16.681 [INFO] field_friend/automations/implements/weeding_implement.py:154: Moved weed 57f77f9c-5fcb-498c-9793-8393e65d7486 from Point(0.0, -0.03) to Point(0.0, -0.03) by 0.006885315488495594 to safe 9a78e552-4615-4daa-894c-3a818fbc6316 at Point(0.0, 0.0)
rosys_1       | 2024-07-16 15:40:16.682 [INFO] field_friend/automations/implements/tornado.py:64: Skipping weed because it was already punched
rosys_1       | 2024-07-16 15:40:17.591 [INFO] field_friend/automations/implements/tornado.py:70: Closest crop is out of working area
rosys_1       | 2024-07-16 15:40:24.643 [WARNING] rosys/hardware/estop.py:56: E-Stop [0] changed
```

**Comment by LukasBaecker** [comment]
Same happened in Follow Crop Mode with new setting as you can see in #103
`rosys_1       | 2024-07-16 17:19:12.518 [INFO] field_friend/automations/plant_locator.py:51: backup: autoupload: Autoupload.FILTERED
rosys_1       | 2024-07-16 17:19:14.690 [INFO] rosys/vision/mjpeg_camera/mjpeg_camera_provider.py:90: activating camera "b8:a4:4f:a9:43:1f-1" at ip "192.168.42.3" ...
rosys_1       | 2024-07-16 17:19:14.691 [INFO] rosys/vision/mjpeg_camera/mjpeg_camera_provider.py:90: activating camera "b8:a4:4f:a9:43:1f-2" at ip "192.168.42.3" ...
rosys_1       | 2024-07-16 17:19:14.691 [INFO] rosys/vision/mjpeg_camera/mjpeg_camera_provider.py:90: activating camera "b8:a4:4f:a9:43:1f-3" at ip "192.168.42.3" ...
rosys_1       | 2024-07-16 17:19:14.692 [INFO] rosys/vision/mjpeg_camera/mjpeg_camera_provider.py:90: activating camera "b8:a4:4f:a9:43:1f-4" at ip "192.168.42.3" ...
rosys_1       | 2024-07-16 17:19:14.692 [INFO] rosys/vision/mjpeg_camera/mjpeg_device.py:44: Capturing images from http://192.168.42.3/axis-cgi/mjpg/video.cgi?camera=1
rosys_1       | 2024-07-16 17:19:14.707 [INFO] rosys/vision/mjpeg_camera/mjpeg_device.py:44: Capturing images from http://192.168.42.3/axis-cgi/mjpg/video.cgi?camera=2
rosys_1       | 2024-07-16 17:19:14.720 [INFO] rosys/vision/mjpeg_camera/mjpeg_device.py:44: Capturing images from http://192.168.42.3/axis-cgi/mjpg/video.cgi?camera=3
rosys_1       | 2024-07-16 17:19:14.732 [INFO] rosys/vision/mjpeg_camera/mjpeg_device.py:44: Capturing images from http://192.168.42.3/axis-cgi/mjpg/video.cgi?camera=4
rosys_1       | 2024-07-16 17:19:15.817 [WARNING] rosys/vision/detector_hardware.py:35: sio connect error on 8004: Connection refused by the server
rosys_1       | 2024-07-16 17:19:15.817 [ERROR] rosys/vision/detector_hardware.py:47: connection to f7797a9f-5244-4b2b-b23b-b8b6e7681cf7 at port 8004 failed; trying again
rosys_1       | 2024-07-16 17:19:17.515 [INFO] field_friend/vision/camera_configurator.py:27: updating camera config
rosys_1       | 2024-07-16 17:19:17.537 [INFO] rosys/hardware/battery_control.py:28: releasing battery relay
rosys_1       | 2024-07-16 17:19:18.517 [INFO] field_friend/vision/camera_configurator.py:36: camera: 32e4-9230-platform-3610000.xhci-usb-0:2.3:1.0 is active
rosys_1       | 2024-07-16 17:19:18.518 [INFO] field_friend/vision/camera_configurator.py:46: parameter width with value 1280
rosys_1       | 2024-07-16 17:19:18.518 [INFO] field_friend/vision/camera_configurator.py:46: parameter height with value 720
rosys_1       | 2024-07-16 17:19:18.518 [INFO] field_friend/vision/camera_configurator.py:46: parameter auto_exposure with value True
rosys_1       | 2024-07-16 17:19:18.519 [INFO] field_friend/vision/camera_configurator.py:46: parameter fps with value 10
rosys_1       | 2024-07-16 17:19:18.519 [INFO] field_friend/vision/camera_configurator.py:48: 9 != 10
rosys_1       | 2024-07-16 17:19:18.519 [INFO] field_friend/vision/camera_configurator.py:98: Updated camera 32e4-9230-platform-3610000.xhci-usb-0:2.3:1.0 parameters, requesting backup...
rosys_1       | 2024-07-16 17:19:18.818 [INFO] rosys/vision/detector_hardware.py:45: trying reconnect f7797a9f-5244-4b2b-b23b-b8b6e7681cf7
rosys_1       | 2024-07-16 17:19:18.819 [INFO] rosys/vision/detector_hardware.py:57: connecting to detector at ws://localhost:8004
rosys_1       | 2024-07-16 17:19:18.843 [INFO] rosys/vision/detector_hardware.py:59: connected successfully
rosys_1       | 2024-07-16 17:19:22.507 [INFO] field_friend/vision/calibratable_usb_camera_provider.py:24: backing up camera: {'id': '32e4-9230-platform-3610000.xhci-usb-0:2.1:1.0', 'name': '32e4-9230-platform-3610000.xhci-usb-0:2.1:1.0', 'connect_after_init': True, 'streaming': False, 'focal_length': 1830, 'calibration': {'intrinsics': {'matrix': [[900.7563580745991, 0.0, 663.0230501520205], [0.0, 904.6425099884107, 301.96771840322316], [0.0, 0.0, 1.0]], 'distortion': [-0.3936727926969431, 0.1910463197137935, 0.004863672318620469, 0.0004754694660314551, -0.04783286390279313], 'rotation': {'R': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'size': {'width': 1280, 'height': 720}}, 'extrinsics': {'rotation': {'R': [[-0.008812065190163532, 0.7845453340130073, -0.6200088437962019], [0.9999610194820463, 0.007257303739787835, -0.005029021659822479], [0.0005540970229195576, -0.620028991597044, -0.7845787038631892]]}, 'translation': [0.2925151857987712, 0.014639470490577467, 0.3090187031839868]}}, 'auto_exposure': True, 'exposure': False, 'width': 1280, 'height': 720, 'fps': 9}
rosys_1       | 2024-07-16 17:19:22.511 [INFO] field_friend/vision/calibratable_usb_camera_provider.py:24: backing up camera: {'id': '32e4-9230-platform-3610000.xhci-usb-0:2.3:1.0', 'name': '32e4-9230-platform-3610000.xhci-usb-0:2.3:1.0', 'connect_after_init': True, 'streaming': True, 'focal_length': 1830, 'calibration': {'intrinsics': {'matrix': [[900.7563580745991, 0.0, 663.0230501520205], [0.0, 904.6425099884107, 301.96771840322316], [0.0, 0.0, 1.0]], 'distortion': [-0.3936727926969431, 0.1910463197137935, 0.004863672318620469, 0.0004754694660314551, -0.04783286390279313], 'rotation': {'R': [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]}, 'size': {'width': 1280, 'height': 720}}, 'extrinsics': {'rotation': {'R': [[-0.008812065190163532, 0.7845453340130073, -0.6200088437962019], [0.9999610194820463, 0.007257303739787835, -0.005029021659822479], [0.0005540970229195576, -0.620028991597044, -0.7845787038631892]]}, 'translation': [0.2925151857987712, 0.014639470490577467, 0.3090187031839868]}}, 'auto_exposure': True, 'exposure': False, 'width': 1280, 'height': 720, 'fps': 9}
rosys_1       | 2024-07-16 17:19:24.741 [INFO] rosys/rosys.py:69: automation started
rosys_1       | 2024-07-16 17:19:24.743 [INFO] field_friend/automations/navigation/follow_crops_navigation.py:30: Activating Recorder...
rosys_1       | 2024-07-16 17:20:02.570 [WARNING] rosys/rosys.py:232: less than 300 mb of memory remaining -> start garbage collection
rosys_1       | 2024-07-16 17:20:02.959 [INFO] field_friend/localization/gnss_hardware.py:102: Parse error: ('could not parse data', '$')
rosys_1       | 2024-07-16 17:20:02.966 [WARNING] field_friend/localization/gnss_hardware.py:109: No location in GNSS data -- maybe it was provided in GGA message?
rosys_1       | 2024-07-16 17:20:02.967 [WARNING] field_friend/localization/gnss.py:94: new GNSS record is None
rosys_1       | 2024-07-16 17:20:02.967 [INFO] field_friend/automations/automation_watcher.py:62: not pausing automation because GNSS connection lost but GNSS watch is not active
rosys_1       | 2024-07-16 17:20:03.941 [WARNING] rosys/rosys.py:235: finished garbage collection
rosys_1       | 2024-07-16 17:21:00.983 [INFO] rosys/rosys.py:69: automation paused because pause button was pressed`

**Comment by rodja** [comment]
@pascalzauberzeug is it really happening with "straight line navigation"? With "follow crops" I can imagine how a constellation of crops could lead to such a turn. But with "straight line" I've never experienced it before. If it does happen with "straight line", I think we need much more detailed logging to get to the bottom of this.

Both your logs show `new GNSS record is None`. Have you picked the logs because of this message or are the logs truly the time where the robot made it turn? To verify the behaviour with lost signal, I created https://github.com/zauberzeug/field_friend/pull/124. It does not turn the robot.

**Comment by pascalzauberzeug** [comment]
@rodja Yes, I ran F13 only on straight line. The log I posted is just the minute before I pressed the e-stop

**Comment by rodja** [comment]
Could you add more logging? Like the yaw change when calling the `_drive` method? Or maybe activate serial logging so we can find out what is send to the motors when the turn happens...
